services:
  caddy:
    image: caddy:2-alpine
    container_name: dzencode_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    environment:
      - SSL_DOMAIN=${SSL_DOMAIN}
      - SITE_PORT=${SITE_PORT}
    volumes:
      - ./_docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx

volumes:
  caddy_data:
  caddy_config:
